stages:
  - test

test_playwright:
  image: mcr.microsoft.com/playwright:focal
  stage: test
  script:
    - npm install
    - npx playwright install
    - npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-report/
    expire_in: 1 week 