name: Playwright Tests

on:
  push:
    branches:
      - main
      - cicd-adjustments
  pull_request:
    branches:
      - main
      - cicd-adjustments

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Check Node.js and npm version
      run: |
        node -v
        npm -v

    - name: Install dependencies
      run: npm install

    - name: Set permissions for node_modules
      run: chmod -R 755 node_modules

    - name: Install Playwright browsers
      shell: bash
      run: npx playwright install

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload Playwright report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: playwright-report/ 
